### ISSUE TITLE
When will Rosetta support nested key/value pairs? Or does it already?

### ISSUE THREAD

**Issue by samreid** [phetsims/rosetta#466]
From https://github.com/phetsims/chipper/issues/1588 I noticed that CaV has a yaml file with:

```yaml
keyboardHelpDialog.move: Move
keyboardHelpDialog.endOfNumberLine: end of number line
keyboardHelpDialog.startOfNumberLine: start of number line
keyboardHelpDialog.grabOrReleaseBall: Grab or Release Ball
keyboardHelpDialog.moveGrabbedBallTitle: Move Grabbed Ball
keyboardHelpDialog.moveGrabbedBall: Move grabbed ball
keyboardHelpDialog.grabOrRelease: Grab or release
keyboardHelpDialog.jumpToStartOfNumberLine: Jump to start of number line
keyboardHelpDialog.jumpToEndOfNumberLine: Jump to end of number line
keyboardHelpDialog.jumpBallToTickMark: Jump ball to tick mark
```

And was wondering if we could switch it to:

```yaml
keyboardHelpDialog:
  move: Move
  endOfNumberLine: end of number line
  startOfNumberLine: start of number line
  grabOrReleaseBall: Grab or Release Ball
  moveGrabbedBallTitle: Move Grabbed Ball
  moveGrabbedBall: Move grabbed ball
  grabOrRelease: Grab or release
  jumpToStartOfNumberLine: Jump to start of number line
  jumpToEndOfNumberLine: Jump to end of number line
  jumpBallToTickMark: Jump ball to tick mark
```

For this release.

Note the latter has JSON like so:

```json
  "keyboardHelpDialog": {
    "move": {
      "value": "Move"
    },
    "endOfNumberLine": {
      "value": "end of number line"
    },
```

Heads up to @marlitas @jessegreenberg, but I'll assign to @jbphet and @AgustinVallejo for the question. When will Rosetta support nested key/value pairs? Or does it already? Thanks!
